### PR TITLE
Added alias for creating branches.

### PR DESCRIPTION
**Pull request by nikhilagrawaldotnet**
As discussed in https://github.com/cake-contrib/Cake_Git/issues/52 added option for creating branches.

### CODE REVIEW

**Comment by devlead** [comment]
@nikhilagrawaldotnet thanks for you contribution! 👍  could you please add an integration tests for this in [test.cake](https://github.com/cake-contrib/Cake_Git/blob/develop/test.cake) and rebase against latest develop.

**Comment by nikhilagrawaldotnet** [comment]
@devlead Done.

**Comment by devlead** [comment]
@nikhilagrawaldotnet  your changes have been merged, thanks for your contribution 👍

An artifact should be on the myget feed ( see https://myget.org/feed/cake-contrib/package/nuget/Cake.Git ) as soon as CI finishes.

**Comment by nikhilagrawaldotnet** [comment]
Awesome. Thanks. :)

**Pull request merged**
