### PR TITLE
Bump dependencies

### LINKED ISSUE #100: Recommended changes resulting from automated audit
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [ ] You are currently referencing Cake.Core 0.28.1. Please upgrade to 0.33.0
- [ ] The nuget package for your addin should use the cake-contrib icon. Specifically, your addin's `.csproj` should have a line like this: `<PackageIconUrl>https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/cake-contrib-medium.png</PackageIconUrl>`.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.

This issue was created by a tool: Cake.AddinDiscoverer version 3.12.1

### LINKED ISSUE #101: Bump dependencies to reduce Cake warnings

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #100 & #101

### CODE REVIEW

**Comment by gitfool** [comment]
Note: I had to bump the Travis Ubuntu environment to get the build to work.

**Comment by linqcan** [comment]
Would also appreciate this change!

**Comment by mxplusb** [comment]
Would be good to see  this pushed through.

**Comment by daghb** [comment]
@pascalberger - any idea on when this may be merged?

**Review by pascalberger — APPROVED** [review]
While I prefer to still test against Ubuntu 14.04, I'm OK with merging this an publishing a release to have compatibility with Cake 0.33.0 and have later a look if we can get tests running again against Ubuntu 14.04.

**Comment by pascalberger** [comment]
@gitfool your changes have been merged, thanks for your contribution 👍

**Pull request merged**
