### PR TITLE
Add git clean command

### PR DESCRIPTION
**Pull request by mbeelman**
This change is based on #35

### CODE REVIEW

**Comment by devlead** [comment]
@nikhilagrawaldotnet I'm sorry haven't had a chance to take a look at this yet. Ping back as soon as I've done that.

**Review by nikhilagrawaldotnet — APPROVED** [review]
Changes LGTM :+1:

**Comment by nikhilagrawaldotnet** [comment]
@devlead : Now?

**Comment by devlead** [comment]
@mbeelman your changes have been merged, thanks for your contribution 👍

**Pull request merged**
