### PR TITLE
Update to LibGit2Sharp v0.27.0-preview-0102

### LINKED ISSUE #145: Access violation calling GitHasUncommitedChanges
This was working fine last week, not sure what changed, but calling GitHasUncommitedChanges on v1.0.1 throws the following exception:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at LibGit2Sharp.Core.NativeMethods.git_status_list_new(LibGit2Sharp.Core.git_status_list* ByRef, LibGit2Sharp.Core.git_repository*, LibGit2Sharp.Core.GitStatusOptions)
--------------------------------
   at LibGit2Sharp.Core.Proxy.git_status_list_new(LibGit2Sharp.Core.Handles.RepositoryHandle, LibGit2Sharp.Core.GitStatusOptions)
   at LibGit2Sharp.RepositoryStatus..ctor(LibGit2Sharp.Repository, LibGit2Sharp.StatusOptions)
   at LibGit2Sharp.RepositoryExtensions.RetrieveStatus(LibGit2Sharp.IRepository)
   at Cake.Git.GitAliases+<>c.<GitHasUncommitedChanges>b__38_0(LibGit2Sharp.Repository)
   at Cake.Git.Extensions.RepositoryExtensions.UseRepository[[System.Boolean, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Cake.Core.ICakeContext, Cake.Core.IO.DirectoryPath, System.Func`2<LibGit2Sharp.Repository,Boolean>)
   at Cake.Git.GitAliases.GitHasUncommitedChanges(Cake.Core.ICakeContext, Cake.Core.IO.DirectoryPath)
```

### PR DESCRIPTION
**Pull request by augustoproiete**
Closes https://github.com/cake-contrib/Cake_Git/issues/145

### CODE REVIEW

**Review by nils-a — APPROVED** [review]
LGTM

**Comment by lprichar** [comment]
Hi.  I recently upgraded my build server to Ubuntu 20 and am now getting the error "The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception" from Cake.Git.  The team [over there](https://github.com/libgit2/libgit2sharp/issues/1839) said the problem is fixed in v0.27.0-preview-0102, and so this PR should fix my problem.  

May I kindly ask when this PR is scheduled to merge and publish back out to NuGet?

**Comment by augustoproiete** [comment]
@lprichar New release should be out in a few days, but in the meantime, as a possible workaround (I haven't tested it), you might be able to force loading LibGit2Sharp v0.27.0-preview-0102 in your Cake script before Cake.Git gets loaded:

```cakescript
#addin "nuget:?package=LibGit2Sharp&version=0.27.0-preview-0102&prerelease&loaddependencies=true"
#addin "nuget:?package=Cake.Git&version=1.0.1"
// ...
```

**Comment by lprichar** [comment]
@augustoproiete Great idea for a hack, unfortunately that produces "Cannot implicitly convert type 'System.Collections.Generic.List<LibGit2Sharp.Tag>' to 'System.Collections.Generic.List<LibGit2Sharp.Tag>'", which is meaningless to me, but undoubtedly is a side-effect of multiple versions of LibGit2Sharp hanging around.

**Comment by devlead** [comment]
@augustoproiete  your changes have been merged, thanks for your contribution 👍

As TravisCI no longer is OSS free, added GitHub actions ubuntu-18.04, ubuntu-latest, and macos-latest to test this PR.

Net4x also needed latest version to work on ubuntu.

**Comment by augustoproiete** [comment]
Great. Thanks @devlead!

@lprichar Cake.Git v1.1.0 is out on NuGet

**Comment by lprichar** [comment]
🎉 thank you!

**Pull request merged**
