### PR TITLE
Add Basic Support for git Configuration Commands

### LINKED ISSUE #37: Add support for reading configuration values
It would be nice to have support for reading configuration values (eg. username, email). Basically just a wrapper around `Repository.Config.GetValueOrDefault`.

### PR DESCRIPTION
**Pull request by kdelorey**
Allow basic ability to get, set, and unset git configuration.

Resolves #37

### CODE REVIEW

**Comment by kdelorey** [comment]
Anyone have a chance to review this? I could really use it on a project.

@pascalberger maybe?

**Review by nils-a — APPROVED** [review]
LGTM!

**Comment by nils-a** [comment]
@kdelorey your changes have been merged, thanks for your contribution :+1:

**Comment by kdelorey** [comment]
Sweet, thanks @nils-a!

**Pull request merged**
