### PR TITLE
Update to LibGit2Sharp 0.30.0

### PR DESCRIPTION
**Pull request by pascalberger**
Update to LibGit2Sharp 0.30.0 and native binaries 2.0.322

### CODE REVIEW

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by joakimia** [comment]
Can this be merged?
Hoping that this solves #165  / #79 for M1 / M2 Macs

**Comment by pascalberger** [comment]
> Hoping that this solves #165 / #79 for M1 / M2 Macs

This won't fix issue when running in Cake Scripting on M1/M2 processor, since this is caused by how the Cake loads the DLLs / how they are packaged in this addin. It already works with the current version of the addin for Cake Frosting.

**Review by devlead — APPROVED** [review]
LGTM

**Comment by devlead** [comment]
@pascalberger  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
