### PR TITLE
(GH-22) Inconsistency between GitClone aliases

### LINKED ISSUE #22: Inconsistency between GitClone aliases
As noted on this StackOverflow question/answer:

http://stackoverflow.com/questions/41048037/how-can-i-go-a-git-clone-operation-using-cake

There are two aliases for `GitClone` that accept a username/password.  These aliases don't create the directory that is being cloned into, which is inconsistent compared to the other aliases.

Can these be made the same?

### PR DESCRIPTION
**Pull request by Roadrunner67**
Fixes #22

### CODE REVIEW

**Review by Marat-Gumerov — APPROVED** [review]
Lost a half of day in cause of this bug (

**Review by Marat-Gumerov — APPROVED** [review]

**Comment by Roadrunner67** [comment]
@Marat-Gumerov can you pls. approve the merge?

**Review by Marat-Gumerov — APPROVED** [review]

**Comment by Marat-Gumerov** [comment]
Looks like I can't)

**Comment by Roadrunner67** [comment]
I hope we must not wait another 7 months...

**Comment by Roadrunner67** [comment]
@pascalberger @devlead - any thoughts?

**Comment by soroshsabz** [comment]
Any news for this PR?

**Review by pascalberger — APPROVED** [review]
LGTM

**Comment by pascalberger** [comment]
@Roadrunner67 Sorry for the long wait. Your changes have been merged, thanks for your contribution 👍

**Pull request merged**
