### PR TITLE
WIP .NET Core support

### PR DESCRIPTION
**Pull request by devlead**
- [x] Port to VS2017
- [x] Multitarget .NET Core & .NET Full
- [x] Port build & test script to .NET Core 
- [x] Currently something like cake-build/cake#1695 is needed to be able to use lib & framwork moniker.
~~- [ ] Seeing issues with .NET Core not finding / looking for native assemblies in same places as Full .NET.~~
_Currently limited to x64 support on .NET Core Windows, because native framework path issues_

### CODE REVIEW

**Comment by patriksvensson** [comment]
@devlead FYI: cake-build/cake#1695 has been merged into develop.

**Comment by devlead** [comment]
@patriksvensson confirmed working with 0.22.0-alpha0075

**Comment by RLittlesII** [comment]
@devlead Is this at a point you can merge?  I just realized while running Cake.Recipe today that it depends on this addin.

**Comment by devlead** [comment]
@RLittlesII all dependencies are now out of pre-release, so I'll just need some time, been traveling but back now so can hopefully sort it during next week.

**Comment by Kemyke** [comment]
Hey guys,
do you have any plan when this PR will be merged? We are really waiting to use the Git functionality on our Linux build agent.

Thx!

**Comment by jefflequeux** [comment]
Is there any achange to merge that pull request?

**Comment by devlead** [comment]
Fixed by just released 0.19.0

**Pull request closed without merging**
